/**
 * EarthSignal - Observation cell catalog and post-event design examples.
 */

import { GeoCell, PostEventEvaluation } from '../types';
import { generateCellSocialSummary } from './snsCollector';

type CellCatalogEntry = Pick<
  GeoCell,
  'id' | 'h3Index' | 'name' | 'region' | 'prefecture' | 'center' | 'svgCoordinates'
>;

export const CELL_CATALOG: CellCatalogEntry[] = [
  {
    id: 'cell_tokyo_01',
    h3Index: '882f5a0921fffff',
    name: '東京都心・東京湾岸エリア',
    region: '関東',
    prefecture: '東京都',
    center: { latitude: 35.6812, longitude: 139.7671 },
    svgCoordinates: { x: 575, y: 440 },
  },
  {
    id: 'cell_chiba_02',
    h3Index: '882f5a0937fffff',
    name: '千葉県東部・九十九里沿岸',
    region: '関東',
    prefecture: '千葉県',
    center: { latitude: 35.5342, longitude: 140.4501 },
    svgCoordinates: { x: 610, y: 445 },
  },
  {
    id: 'cell_noto_03',
    h3Index: '882f5a0953fffff',
    name: '石川県能登半島・輪島沖エリア',
    region: '中部',
    prefecture: '石川県',
    center: { latitude: 37.4012, longitude: 136.9014 },
    svgCoordinates: { x: 505, y: 350 },
  },
  {
    id: 'cell_miyagi_04',
    h3Index: '882f5a0965fffff',
    name: '宮城県仙台・三陸沿岸エリア',
    region: '東北',
    prefecture: '宮城県',
    center: { latitude: 38.2682, longitude: 140.8694 },
    svgCoordinates: { x: 615, y: 310 },
  },
  {
    id: 'cell_osaka_05',
    h3Index: '882f5a0989fffff',
    name: '大阪平野・阪神エリア',
    region: '近畿',
    prefecture: '大阪府',
    center: { latitude: 34.6937, longitude: 135.5023 },
    svgCoordinates: { x: 445, y: 465 },
  },
  {
    id: 'cell_miyazaki_06',
    h3Index: '882f5a09a1fffff',
    name: '宮崎県・日向灘沿岸エリア',
    region: '九州',
    prefecture: '宮崎県',
    center: { latitude: 31.9077, longitude: 131.4202 },
    svgCoordinates: { x: 310, y: 550 },
  },
  {
    id: 'cell_hokkaido_07',
    h3Index: '882f5a09b5fffff',
    name: '北海道・胆振・石狩平野エリア',
    region: '北海道',
    prefecture: '北海道',
    center: { latitude: 43.0618, longitude: 141.3545 },
    svgCoordinates: { x: 620, y: 150 },
  },
  {
    id: 'cell_okinawa_08',
    h3Index: '882f5a09c9fffff',
    name: '沖縄本島・那覇周辺エリア',
    region: '沖縄',
    prefecture: '沖縄県',
    center: { latitude: 26.2124, longitude: 127.6809 },
    svgCoordinates: { x: 180, y: 620 },
  },
];

function createEmptyGeoCell(entry: CellCatalogEntry): GeoCell {
  return {
    ...entry,
    recentObservationsCount: 0,
    socialSummary: generateCellSocialSummary(entry.id, [], '6h'),
    weather: {
      cellId: entry.id,
      observedAt: '',
      cloudCoverTotal: 0,
      cloudCoverLow: 0,
      cloudCoverMid: 0,
      cloudCoverHigh: 0,
      pressureMsl: 0,
      surfacePressure: 0,
      pressureChange24h: 0,
      relativeHumidity: 0,
      precipitation: 0,
      windSpeed: 0,
      windDirection: 0,
      temperature: 0,
      weatherCode: 0,
      fetchedAt: '',
      isStale: true,
    },
    currentScore: {
      scoreAt: '',
      scoreVersion: 'score-v4-local-24h',
      status: 'insufficient',
      overallScore: null,
      qualityScore: 0,
      sampleCount: 0,
      earthquakeActivityScore: null,
      weatherScore: null,
      socialScore: null,
      animalAudioScore: null,
      otherAudioScore: null,
      citizenReportScore: null,
      contributors: [],
      confounders: ['ライブデータと実測ベースラインを取得中'],
      explanationText: 'ライブ観測データを取得中です。取得完了までは異常度を表示しません。',
    },
  };
}

/** ライブ画面用に、参照を共有しない未取得状態の地域セルを作る。 */
export function createRuntimeGeoCells(): GeoCell[] {
  return CELL_CATALOG.map(createEmptyGeoCell);
}

/** サーバー側のセルID・座標許可リスト。値はすべて未取得状態。 */
export const INITIAL_GEO_CELLS: GeoCell[] = createRuntimeGeoCells();

// 事後検証画面のUI・統計出力形式を確認するための設計例（実研究結果ではない）
export const POST_EVENT_EVALUATIONS: PostEventEvaluation[] = [
  {
    id: 'eval_noto_20240101',
    earthquake: {
      id: 'eq_noto_m76',
      occurredAt: '2024-01-01T07:10:00Z',
      hypocenterName: '石川県能登地方 (M7.6 最大震度7)',
      latitude: 37.5,
      longitude: 137.2,
      depthKm: 16,
      magnitude: 7.6,
      maxIntensity: '7',
      tsunamiStatus: 'major_warning',
      source: 'jma',
      revision: 3,
      updatedAt: '2024-01-01T07:30:00Z',
    },
    analysisWindow: '24h',
    evaluatedAt: '2024-01-08T00:00:00Z',
    cellId: 'cell_noto_03',
    cellName: '石川県能登半島・輪島沖エリア',
    distanceFromEpicenterKm: 28,
    metrics: [
      {
        featureName: 'dog_bark_events',
        displayName: '犬の鳴き声イベント頻度',
        preEventValue: 6.8,
        controlMedian: 5.9,
        changePercentage: +15.2,
        confidenceInterval95: [-8.4, +41.5],
        isStatisticallySignificant: false,
      },
      {
        featureName: 'cloud_cover_high',
        displayName: '上層雲量(巻雲系)',
        preEventValue: 62.0,
        controlMedian: 58.0,
        changePercentage: +6.9,
        confidenceInterval95: [-12.0, +26.0],
        isStatisticallySignificant: false,
      },
      {
        featureName: 'pressure_trend_3h',
        displayName: '気圧変動トレンド(3h)',
        preEventValue: -1.2,
        controlMedian: -0.9,
        changePercentage: +33.3,
        confidenceInterval95: [-15.0, +82.0],
        isStatisticallySignificant: false,
      },
      {
        featureName: 'micro_seismic_rate',
        displayName: '周辺微小地震活動(M1.5+)',
        preEventValue: 14.0,
        controlMedian: 3.2,
        changePercentage: +337.5,
        confidenceInterval95: [+180.0, +520.0],
        isStatisticallySignificant: true,
      },
    ],
    verdict: 'significant_deviation_unverified_causality',
    verdictSummary: '微小地震活動の統計的有意な上昇が確認された一方、動物音響・雲量については95%信頼区間がゼロを跨ぎ、平常時対照期間との間に明確な因果的差異は確認されませんでした。',
    scientificNotes: '地震活動（前震群）自体のクラスタリングは明瞭ですが、民間SNS等で話題となった「動物異常行動」や「地震雲」についての客観データ指標は対照群（同季節・同時間帯）の標準偏差範囲内に収まっており、事後バイアス（想起バイアス）の可能性が強く示唆されます。',
  },
  {
    id: 'eval_chiba_20240301',
    earthquake: {
      id: 'eq_chiba_m53',
      occurredAt: '2024-03-01T20:22:00Z',
      hypocenterName: '千葉県東方沖 (M5.3 最大震度4)',
      latitude: 35.3,
      longitude: 140.6,
      depthKm: 25,
      magnitude: 5.3,
      maxIntensity: '4',
      tsunamiStatus: 'none',
      source: 'p2pquake',
      revision: 1,
      updatedAt: '2024-03-01T20:25:00Z',
    },
    analysisWindow: '72h',
    evaluatedAt: '2024-03-05T00:00:00Z',
    cellId: 'cell_chiba_02',
    cellName: '千葉県東部・九十九里沿岸',
    distanceFromEpicenterKm: 42,
    metrics: [
      {
        featureName: 'dog_bark_events',
        displayName: '犬の鳴き声イベント頻度',
        preEventValue: 7.2,
        controlMedian: 7.0,
        changePercentage: +2.8,
        confidenceInterval95: [-14.0, +22.0],
        isStatisticallySignificant: false,
      },
      {
        featureName: 'bird_vocalizations',
        displayName: '野鳥・カラスの鳴き声頻度',
        preEventValue: 12.4,
        controlMedian: 11.8,
        changePercentage: +5.1,
        confidenceInterval95: [-9.0, +21.0],
        isStatisticallySignificant: false,
      },
      {
        featureName: 'cloud_shape_reports',
        displayName: '市民クラウド投稿数',
        preEventValue: 18.0,
        controlMedian: 4.2,
        changePercentage: +328.0,
        confidenceInterval95: [+140.0, +580.0],
        isStatisticallySignificant: true,
      },
    ],
    verdict: 'mild_anomaly_weather_confounded',
    verdictSummary: '市民による雲の違和感投稿が急増していましたが、同時刻に前線通過に伴う高積雲（波状雲）の気象発生条件と完全に一致しており、気象学的要因による説明が妥当と結論付けられました。',
    scientificNotes: '気圧・風向データの交絡補正を行うと、市民投稿の増加は「気象前線による特殊な波状雲の出現」を原因とするものであり、地下地殻変動との直接の因果性は裏付けられませんでした。',
  },
  {
    id: 'eval_false_positive_202511',
    earthquake: {
      id: 'eq_hypothetical_fp',
      occurredAt: '2025-11-14T00:00:00Z',
      hypocenterName: '【偽陽性検証事例】観測異常度高(78)も地震発生なし',
      latitude: 35.6,
      longitude: 139.7,
      depthKm: null,
      magnitude: null,
      maxIntensity: null,
      tsunamiStatus: 'none',
      source: 'jma',
      revision: 1,
      updatedAt: '2025-11-18T00:00:00Z',
    },
    analysisWindow: '72h',
    evaluatedAt: '2025-11-18T00:00:00Z',
    cellId: 'cell_tokyo_01',
    cellName: '東京都心・東京湾岸エリア',
    distanceFromEpicenterKm: 0,
    metrics: [
      {
        featureName: 'dog_bark_events',
        displayName: '犬の鳴き声イベント頻度',
        preEventValue: 14.5,
        controlMedian: 5.2,
        changePercentage: +178.8,
        confidenceInterval95: [+95.0, +280.0],
        isStatisticallySignificant: true,
      },
      {
        featureName: 'sound_clipping_events',
        displayName: '低周波環境音響',
        preEventValue: 18.2,
        controlMedian: 6.0,
        changePercentage: +203.3,
        confidenceInterval95: [+110.0, +310.0],
        isStatisticallySignificant: true,
      },
    ],
    verdict: 'no_clear_deviation',
    verdictSummary: '犬の鳴き声と低周波音の観測異常度が78まで急上昇したものの、地震は発生しませんでした。調査の結果、近隣の大規模花火大会・屋外フェスによる音響交絡であることが判明しました。',
    scientificNotes: '科学的説明責任に基づき、地震が起きなかった「偽陽性事例」をカタログ保存しています。人間活動や気象イベントによる交絡因子をリアルタイム分離する重要性を示す重要サンプルです。',
  },
];
