/**
 * EarthSignal - Data Store & Seed Service
 * Manages GeoCells, Real-time P2P Earthquake feeds, Open-Meteo weather, and Post-event datasets
 */

import { Earthquake, GeoCell, Observation, PostEventEvaluation, WeatherObservation } from '../types';
import { computeCellScore, FeatureInput } from './anomalyEngine';
import { generateCellSocialSummary, SAMPLE_SOCIAL_POSTS } from './snsCollector';

// 初期地域セルマスター (H3風六角形メッシュ & 日本地図SVG座標)
export const INITIAL_GEO_CELLS: GeoCell[] = [
  {
    id: 'cell_tokyo_01',
    h3Index: '882f5a0921fffff',
    name: '東京都心・東京湾岸エリア',
    region: '関東',
    prefecture: '東京都',
    center: { latitude: 35.6812, longitude: 139.7671 },
    svgCoordinates: { x: 575, y: 440 },
    recentObservationsCount: 42,
    socialSummary: generateCellSocialSummary('cell_tokyo_01', SAMPLE_SOCIAL_POSTS, '6h'),
    weather: {
      cellId: 'cell_tokyo_01',
      observedAt: new Date().toISOString(),
      cloudCoverTotal: 68,
      cloudCoverLow: 25,
      cloudCoverMid: 40,
      cloudCoverHigh: 72,
      pressureMsl: 1012.4,
      surfacePressure: 1008.2,
      pressureChange24h: -3.8,
      relativeHumidity: 62,
      precipitation: 0.0,
      windSpeed: 3.8,
      windDirection: 180,
      temperature: 24.5,
      weatherCode: 3,
      fetchedAt: new Date().toISOString(),
    },
    currentScore: {
      scoreAt: new Date().toISOString(),
      scoreVersion: 'score-v2-robust',
      status: 'available',
      overallScore: 56.4,
      qualityScore: 0.84,
      sampleCount: 48,
      earthquakeActivityScore: 42.0,
      weatherScore: 51.5,
      socialScore: 68.0,
      animalAudioScore: 68.4,
      otherAudioScore: 45.0,
      citizenReportScore: 52.0,
      contributors: [
        { featureName: 'sns_animal_bark', displayName: 'SNS動物鳴き声投稿頻度', changeRate: '+110%', zScore: 2.15, contribution: 68.0, note: 'Bluesky/Mastodon 12件 (普段比 2.1倍)' },
        { featureName: 'dog_bark_rate', displayName: '音響AI 犬の鳴き声頻度', changeRate: '+85%', zScore: 1.82, contribution: 68.4, note: '平常同時間帯中央値 4.2件/h → 現在 7.8件/h' },
        { featureName: 'cloud_high_ratio', displayName: '上層雲量(巻雲系)', changeRate: '+45%', zScore: 1.25, contribution: 51.5, note: '平常 50% → 現在 72%' },
        { featureName: 'seismic_m2_count', displayName: '微小地震活動(M2+)', changeRate: '+30%', zScore: 0.95, contribution: 42.0, note: '半径50km以内 過去24h 2回' },
      ],
      confounders: ['夕方帰宅ラッシュに伴う生活音増加の可能性', '気圧緩やか低下傾向'],
      explanationText: '犬の鳴き声イベントおよびSNS集合知の言及頻度が過去30日同時間帯中央値より多く検出されていますが、生活時間帯による影響も考えられます。総合観測異常度は 56.4 / 100 (品質: 0.84) です。※地震発生確率ではありません。',
    },
  },
  {
    id: 'cell_chiba_02',
    h3Index: '882f5a0937fffff',
    name: '千葉県東部・九十九里沿岸',
    region: '関東',
    prefecture: '千葉県',
    center: { latitude: 35.5342, longitude: 140.4501 },
    svgCoordinates: { x: 610, y: 445 },
    recentObservationsCount: 28,
    socialSummary: generateCellSocialSummary('cell_chiba_02', SAMPLE_SOCIAL_POSTS, '6h'),
    weather: {
      cellId: 'cell_chiba_02',
      observedAt: new Date().toISOString(),
      cloudCoverTotal: 84,
      cloudCoverLow: 45,
      cloudCoverMid: 60,
      cloudCoverHigh: 88,
      pressureMsl: 1010.8,
      surfacePressure: 1009.5,
      pressureChange24h: -5.2,
      relativeHumidity: 78,
      precipitation: 0.5,
      windSpeed: 5.4,
      windDirection: 140,
      temperature: 23.8,
      weatherCode: 61,
      fetchedAt: new Date().toISOString(),
    },
    currentScore: {
      scoreAt: new Date().toISOString(),
      scoreVersion: 'score-v2-robust',
      status: 'available',
      overallScore: 69.5,
      qualityScore: 0.76,
      sampleCount: 34,
      earthquakeActivityScore: 74.0,
      weatherScore: 62.0,
      socialScore: 72.0,
      animalAudioScore: 72.5,
      otherAudioScore: 50.0,
      citizenReportScore: 65.0,
      contributors: [
        { featureName: 'seismic_swarm_rate', displayName: '周辺微小地震活動', changeRate: '+160%', zScore: 2.35, contribution: 74.0, note: '沖合でM2〜M3クラスが過去48時間で4回観測' },
        { featureName: 'sns_cloud_anomaly', displayName: 'SNS変な雲・地鳴り報告', changeRate: '+135%', zScore: 2.20, contribution: 72.0, note: 'Mastodon/YouTube等で複数報告' },
        { featureName: 'bird_vocalization_rate', displayName: 'カラス・野鳥鳴き声', changeRate: '+110%', zScore: 2.10, contribution: 72.5, note: '早朝・昼間の鳥類検出率が平常の2.1倍' },
      ],
      confounders: ['沿岸強風(5.4m/s)による音響品質補正適用', '気圧低下傾向'],
      explanationText: '沖合での微小地震活動とSNSでの雲・音響に関する言及が平常中央値より高い水準にあります。総合観測異常度は 69.5 / 100 (品質: 0.76) です。※地震の予知や発生確率を示すものではありません。',
    },
  },
  {
    id: 'cell_noto_03',
    h3Index: '882f5a0953fffff',
    name: '石川県能登半島・輪島沖エリア',
    region: '中部',
    prefecture: '石川県',
    center: { latitude: 37.4012, longitude: 136.9014 },
    svgCoordinates: { x: 505, y: 350 },
    recentObservationsCount: 31,
    socialSummary: generateCellSocialSummary('cell_noto_03', SAMPLE_SOCIAL_POSTS, '6h'),
    weather: {
      cellId: 'cell_noto_03',
      observedAt: new Date().toISOString(),
      cloudCoverTotal: 45,
      cloudCoverLow: 20,
      cloudCoverMid: 30,
      cloudCoverHigh: 40,
      pressureMsl: 1014.2,
      surfacePressure: 1012.0,
      pressureChange24h: +1.2,
      relativeHumidity: 55,
      precipitation: 0.0,
      windSpeed: 2.6,
      windDirection: 290,
      temperature: 21.0,
      weatherCode: 2,
      fetchedAt: new Date().toISOString(),
    },
    currentScore: {
      scoreAt: new Date().toISOString(),
      scoreVersion: 'score-v2-robust',
      status: 'available',
      overallScore: 42.0,
      qualityScore: 0.78,
      sampleCount: 26,
      earthquakeActivityScore: 48.0,
      weatherScore: 32.0,
      socialScore: 45.0,
      animalAudioScore: 40.0,
      otherAudioScore: 38.0,
      citizenReportScore: 44.0,
      contributors: [
        { featureName: 'seismic_aftershock_rate', displayName: '地殻活動・余震頻度', changeRate: '+25%', zScore: 0.85, contribution: 48.0, note: '活動は通常推移' },
        { featureName: 'audio_general', displayName: '一般環境音響', changeRate: '-10%', zScore: -0.3, contribution: 38.0, note: '特異な検知なし' },
      ],
      confounders: ['継続的な観測ネットワーク保守中'],
      explanationText: '気象・音響・市民レポートともに平常ベースラインに近い通常推移です。総合観測異常度は 42.0 / 100 (品質: 0.78) です。',
    },
  },
  {
    id: 'cell_miyagi_04',
    h3Index: '882f5a0965fffff',
    name: '宮城県仙台・三陸沿岸エリア',
    region: '東北',
    prefecture: '宮城県',
    center: { latitude: 38.2682, longitude: 140.8694 },
    svgCoordinates: { x: 615, y: 310 },
    recentObservationsCount: 22,
    socialSummary: generateCellSocialSummary('cell_miyagi_04', SAMPLE_SOCIAL_POSTS, '6h'),
    weather: {
      cellId: 'cell_miyagi_04',
      observedAt: new Date().toISOString(),
      cloudCoverTotal: 30,
      cloudCoverLow: 10,
      cloudCoverMid: 20,
      cloudCoverHigh: 35,
      pressureMsl: 1016.0,
      surfacePressure: 1013.5,
      pressureChange24h: +0.8,
      relativeHumidity: 50,
      precipitation: 0.0,
      windSpeed: 2.1,
      windDirection: 90,
      temperature: 22.4,
      weatherCode: 1,
      fetchedAt: new Date().toISOString(),
    },
    currentScore: {
      scoreAt: new Date().toISOString(),
      scoreVersion: 'score-v2-robust',
      status: 'available',
      overallScore: 28.5,
      qualityScore: 0.86,
      sampleCount: 30,
      earthquakeActivityScore: 30.0,
      weatherScore: 25.0,
      socialScore: 26.0,
      animalAudioScore: 29.0,
      otherAudioScore: 26.0,
      citizenReportScore: 28.0,
      contributors: [
        { featureName: 'cloud_variance', displayName: '雲量変動', changeRate: '-15%', zScore: -0.4, contribution: 25.0, note: '快晴ベースライン内' },
      ],
      confounders: [],
      explanationText: '各指標は平常時の中央値付近で安定して推移しています。総合観測異常度は 28.5 / 100 (通常範囲) です。',
    },
  },
  {
    id: 'cell_osaka_05',
    h3Index: '882f5a0989fffff',
    name: '大阪平野・阪神エリア',
    region: '近畿',
    prefecture: '大阪府',
    center: { latitude: 34.6937, longitude: 135.5023 },
    svgCoordinates: { x: 445, y: 465 },
    recentObservationsCount: 36,
    socialSummary: generateCellSocialSummary('cell_osaka_05', SAMPLE_SOCIAL_POSTS, '6h'),
    weather: {
      cellId: 'cell_osaka_05',
      observedAt: new Date().toISOString(),
      cloudCoverTotal: 55,
      cloudCoverLow: 30,
      cloudCoverMid: 35,
      cloudCoverHigh: 60,
      pressureMsl: 1013.0,
      surfacePressure: 1011.2,
      pressureChange24h: -1.5,
      relativeHumidity: 58,
      precipitation: 0.0,
      windSpeed: 3.0,
      windDirection: 220,
      temperature: 26.0,
      weatherCode: 2,
      fetchedAt: new Date().toISOString(),
    },
    currentScore: {
      scoreAt: new Date().toISOString(),
      scoreVersion: 'score-v2-robust',
      status: 'available',
      overallScore: 38.0,
      qualityScore: 0.84,
      sampleCount: 40,
      earthquakeActivityScore: 32.0,
      weatherScore: 36.0,
      socialScore: 38.0,
      animalAudioScore: 44.0,
      otherAudioScore: 42.0,
      citizenReportScore: 36.0,
      contributors: [
        { featureName: 'urban_noise_sound', displayName: '都市環境騒音', changeRate: '+20%', zScore: 0.6, contribution: 42.0, note: '交通量に応じた通常範囲' },
      ],
      confounders: ['都市部の交通ノイズによる音響閾値補正'],
      explanationText: '都市部における平常時の日中ノイズプロファイル内に収まっています。総合観測異常度は 38.0 / 100 です。',
    },
  },
  {
    id: 'cell_miyazaki_06',
    h3Index: '882f5a09a1fffff',
    name: '宮崎県・日向灘沿岸エリア',
    region: '九州',
    prefecture: '宮崎県',
    center: { latitude: 31.9077, longitude: 131.4202 },
    svgCoordinates: { x: 310, y: 550 },
    recentObservationsCount: 20,
    socialSummary: generateCellSocialSummary('cell_miyazaki_06', SAMPLE_SOCIAL_POSTS, '6h'),
    weather: {
      cellId: 'cell_miyazaki_06',
      observedAt: new Date().toISOString(),
      cloudCoverTotal: 72,
      cloudCoverLow: 40,
      cloudCoverMid: 50,
      cloudCoverHigh: 75,
      pressureMsl: 1011.5,
      surfacePressure: 1010.0,
      pressureChange24h: -2.8,
      relativeHumidity: 70,
      precipitation: 0.0,
      windSpeed: 4.1,
      windDirection: 110,
      temperature: 27.2,
      weatherCode: 3,
      fetchedAt: new Date().toISOString(),
    },
    currentScore: {
      scoreAt: new Date().toISOString(),
      scoreVersion: 'score-v2-robust',
      status: 'available',
      overallScore: 59.2,
      qualityScore: 0.74,
      sampleCount: 24,
      earthquakeActivityScore: 62.0,
      weatherScore: 50.0,
      socialScore: 60.0,
      animalAudioScore: 64.0,
      otherAudioScore: 48.0,
      citizenReportScore: 58.0,
      contributors: [
        { featureName: 'hyuganada_micro_eq', displayName: '日向灘深部微小動向', changeRate: '+70%', zScore: 1.45, contribution: 62.0, note: '微小地震イベント数 やや増加' },
        { featureName: 'frog_insect_audio', displayName: '生物音響(夜間昆虫/カエル)', changeRate: '+60%', zScore: 1.30, contribution: 64.0, note: '平常より鳴き声頻度高め' },
      ],
      confounders: ['季節性の虫の声ピーク時間帯'],
      explanationText: '日向灘周辺の微小な地震活動と生物音響が平常中央値をやや上回っています。総合観測異常度は 59.2 / 100 (品質: 0.74) です。',
    },
  },
  {
    id: 'cell_hokkaido_07',
    h3Index: '882f5a09b5fffff',
    name: '北海道・胆振・石狩平野エリア',
    region: '北海道',
    prefecture: '北海道',
    center: { latitude: 43.0618, longitude: 141.3545 },
    svgCoordinates: { x: 620, y: 150 },
    recentObservationsCount: 18,
    socialSummary: generateCellSocialSummary('cell_hokkaido_07', SAMPLE_SOCIAL_POSTS, '6h'),
    weather: {
      cellId: 'cell_hokkaido_07',
      observedAt: new Date().toISOString(),
      cloudCoverTotal: 20,
      cloudCoverLow: 5,
      cloudCoverMid: 10,
      cloudCoverHigh: 25,
      pressureMsl: 1018.0,
      surfacePressure: 1015.0,
      pressureChange24h: +3.0,
      relativeHumidity: 45,
      precipitation: 0.0,
      windSpeed: 2.8,
      windDirection: 340,
      temperature: 18.5,
      weatherCode: 0,
      fetchedAt: new Date().toISOString(),
    },
    currentScore: {
      scoreAt: new Date().toISOString(),
      scoreVersion: 'score-v2-robust',
      status: 'available',
      overallScore: 22.0,
      qualityScore: 0.80,
      sampleCount: 22,
      earthquakeActivityScore: 20.0,
      weatherScore: 21.0,
      socialScore: 22.0,
      animalAudioScore: 24.0,
      otherAudioScore: 22.0,
      citizenReportScore: 23.0,
      contributors: [],
      confounders: [],
      explanationText: '全指標が平常時の基準範囲内で極めて平穏に推移しています。総合観測異常度は 22.0 / 100 です。',
    },
  },
  {
    id: 'cell_okinawa_08',
    h3Index: '882f5a09c9fffff',
    name: '沖縄本島・那覇周辺エリア',
    region: '沖縄',
    prefecture: '沖縄県',
    center: { latitude: 26.2124, longitude: 127.6809 },
    svgCoordinates: { x: 180, y: 620 },
    recentObservationsCount: 6,
    socialSummary: generateCellSocialSummary('cell_okinawa_08', SAMPLE_SOCIAL_POSTS, '6h'),
    weather: {
      cellId: 'cell_okinawa_08',
      observedAt: new Date().toISOString(),
      cloudCoverTotal: 90,
      cloudCoverLow: 70,
      cloudCoverMid: 80,
      cloudCoverHigh: 95,
      pressureMsl: 1006.2,
      surfacePressure: 1005.0,
      pressureChange24h: -8.4,
      relativeHumidity: 88,
      precipitation: 8.5,
      windSpeed: 9.8,
      windDirection: 160,
      temperature: 29.0,
      weatherCode: 65,
      fetchedAt: new Date().toISOString(),
    },
    currentScore: {
      scoreAt: new Date().toISOString(),
      scoreVersion: 'score-v2-robust',
      status: 'insufficient',
      overallScore: null,
      qualityScore: 0.18,
      sampleCount: 6,
      earthquakeActivityScore: null,
      weatherScore: null,
      socialScore: null,
      animalAudioScore: null,
      otherAudioScore: null,
      citizenReportScore: null,
      contributors: [],
      confounders: ['熱帯低気圧通過に伴う暴風雨(9.8m/s, 8.5mm/h)', '有効観測標本数不足(6件)'],
      explanationText: '強風・降水による音響ノイズと観測数の不足のため、統計的信頼性を満たさず「データ不足(品質: 0.18)」としています。',
    },
  },
];

// 初期公式地震データシード (P2P地震情報 / JMA準拠)
export const INITIAL_EARTHQUAKES: Earthquake[] = [
  {
    id: 'eq_p2p_20260827_01',
    occurredAt: '2026-08-27T04:42:10Z',
    hypocenterName: '千葉県東方沖',
    latitude: 35.5,
    longitude: 140.8,
    depthKm: 30,
    magnitude: 4.3,
    maxIntensity: '2',
    tsunamiStatus: 'none',
    source: 'p2pquake',
    sourceEventId: 'p2p_ev_99120',
    revision: 1,
    updatedAt: '2026-08-27T04:45:00Z',
  },
  {
    id: 'eq_p2p_20260826_02',
    occurredAt: '2026-08-26T18:15:33Z',
    hypocenterName: '石川県能登地方',
    latitude: 37.4,
    longitude: 137.0,
    depthKm: 12,
    magnitude: 3.6,
    maxIntensity: '2',
    tsunamiStatus: 'none',
    source: 'p2pquake',
    sourceEventId: 'p2p_ev_99114',
    revision: 1,
    updatedAt: '2026-08-26T18:18:00Z',
  },
  {
    id: 'eq_p2p_20260826_03',
    occurredAt: '2026-08-26T09:22:40Z',
    hypocenterName: '日向灘',
    latitude: 31.8,
    longitude: 131.7,
    depthKm: 35,
    magnitude: 4.8,
    maxIntensity: '3',
    tsunamiStatus: 'none',
    source: 'p2pquake',
    sourceEventId: 'p2p_ev_99102',
    revision: 2,
    updatedAt: '2026-08-26T09:28:00Z',
  },
  {
    id: 'eq_p2p_20260825_04',
    occurredAt: '2026-08-25T22:04:10Z',
    hypocenterName: '宮城県沖',
    latitude: 38.3,
    longitude: 141.6,
    depthKm: 45,
    magnitude: 3.9,
    maxIntensity: '1',
    tsunamiStatus: 'none',
    source: 'p2pquake',
    sourceEventId: 'p2p_ev_99088',
    revision: 1,
    updatedAt: '2026-08-25T22:06:00Z',
  },
  {
    id: 'eq_p2p_20260825_05',
    occurredAt: '2026-08-25T11:49:00Z',
    hypocenterName: 'トカラ列島近海',
    latitude: 29.4,
    longitude: 129.5,
    depthKm: 15,
    magnitude: 3.2,
    maxIntensity: '2',
    tsunamiStatus: 'none',
    source: 'p2pquake',
    sourceEventId: 'p2p_ev_99071',
    revision: 1,
    updatedAt: '2026-08-25T11:51:00Z',
  },
];

// 事後検証 (ケース・コントロール分析) 研究データセット (第24章・25章準拠)
export const POST_EVENT_EVALUATIONS: PostEventEvaluation[] = [
  {
    id: 'eval_noto_20240101',
    earthquake: {
      id: 'eq_noto_m76',
      occurredAt: '2024-01-01T07:10:00Z',
      hypocenterName: '石川県能登地方 (M7.6 最大震度7)',
      latitude: 37.5,
      longitude: 137.2,
      depthKm: 16,
      magnitude: 7.6,
      maxIntensity: '7',
      tsunamiStatus: 'major_warning',
      source: 'jma',
      revision: 3,
      updatedAt: '2024-01-01T07:30:00Z',
    },
    analysisWindow: '24h',
    evaluatedAt: '2024-01-08T00:00:00Z',
    cellId: 'cell_noto_03',
    cellName: '石川県能登半島・輪島沖エリア',
    distanceFromEpicenterKm: 28,
    metrics: [
      {
        featureName: 'dog_bark_events',
        displayName: '犬の鳴き声イベント頻度',
        preEventValue: 6.8,
        controlMedian: 5.9,
        changePercentage: +15.2,
        confidenceInterval95: [-8.4, +41.5],
        isStatisticallySignificant: false,
      },
      {
        featureName: 'cloud_cover_high',
        displayName: '上層雲量(巻雲系)',
        preEventValue: 62.0,
        controlMedian: 58.0,
        changePercentage: +6.9,
        confidenceInterval95: [-12.0, +26.0],
        isStatisticallySignificant: false,
      },
      {
        featureName: 'pressure_trend_3h',
        displayName: '気圧変動トレンド(3h)',
        preEventValue: -1.2,
        controlMedian: -0.9,
        changePercentage: +33.3,
        confidenceInterval95: [-15.0, +82.0],
        isStatisticallySignificant: false,
      },
      {
        featureName: 'micro_seismic_rate',
        displayName: '周辺微小地震活動(M1.5+)',
        preEventValue: 14.0,
        controlMedian: 3.2,
        changePercentage: +337.5,
        confidenceInterval95: [+180.0, +520.0],
        isStatisticallySignificant: true,
      },
    ],
    verdict: 'significant_deviation_unverified_causality',
    verdictSummary: '微小地震活動の統計的有意な上昇が確認された一方、動物音響・雲量については95%信頼区間がゼロを跨ぎ、平常時対照期間との間に明確な因果的差異は確認されませんでした。',
    scientificNotes: '地震活動（前震群）自体のクラスタリングは明瞭ですが、民間SNS等で話題となった「動物異常行動」や「地震雲」についての客観データ指標は対照群（同季節・同時間帯）の標準偏差範囲内に収まっており、事後バイアス（想起バイアス）の可能性が強く示唆されます。',
  },
  {
    id: 'eval_chiba_20240301',
    earthquake: {
      id: 'eq_chiba_m53',
      occurredAt: '2024-03-01T20:22:00Z',
      hypocenterName: '千葉県東方沖 (M5.3 最大震度4)',
      latitude: 35.3,
      longitude: 140.6,
      depthKm: 25,
      magnitude: 5.3,
      maxIntensity: '4',
      tsunamiStatus: 'none',
      source: 'p2pquake',
      revision: 1,
      updatedAt: '2024-03-01T20:25:00Z',
    },
    analysisWindow: '72h',
    evaluatedAt: '2024-03-05T00:00:00Z',
    cellId: 'cell_chiba_02',
    cellName: '千葉県東部・九十九里沿岸',
    distanceFromEpicenterKm: 42,
    metrics: [
      {
        featureName: 'dog_bark_events',
        displayName: '犬の鳴き声イベント頻度',
        preEventValue: 7.2,
        controlMedian: 7.0,
        changePercentage: +2.8,
        confidenceInterval95: [-14.0, +22.0],
        isStatisticallySignificant: false,
      },
      {
        featureName: 'bird_vocalizations',
        displayName: '野鳥・カラスの鳴き声頻度',
        preEventValue: 12.4,
        controlMedian: 11.8,
        changePercentage: +5.1,
        confidenceInterval95: [-9.0, +21.0],
        isStatisticallySignificant: false,
      },
      {
        featureName: 'cloud_shape_reports',
        displayName: '市民クラウド投稿数',
        preEventValue: 18.0,
        controlMedian: 4.2,
        changePercentage: +328.0,
        confidenceInterval95: [+140.0, +580.0],
        isStatisticallySignificant: true,
      },
    ],
    verdict: 'mild_anomaly_weather_confounded',
    verdictSummary: '市民による雲の違和感投稿が急増していましたが、同時刻に前線通過に伴う高積雲（波状雲）の気象発生条件と完全に一致しており、気象学的要因による説明が妥当と結論付けられました。',
    scientificNotes: '気圧・風向データの交絡補正を行うと、市民投稿の増加は「気象前線による特殊な波状雲の出現」を原因とするものであり、地下地殻変動との直接の因果性は裏付けられませんでした。',
  },
  {
    id: 'eval_false_positive_202511',
    earthquake: {
      id: 'eq_hypothetical_fp',
      occurredAt: '2025-11-14T00:00:00Z',
      hypocenterName: '【偽陽性検証事例】観測異常度高(78)も地震発生なし',
      latitude: 35.6,
      longitude: 139.7,
      depthKm: null,
      magnitude: null,
      maxIntensity: null,
      tsunamiStatus: 'none',
      source: 'jma',
      revision: 1,
      updatedAt: '2025-11-18T00:00:00Z',
    },
    analysisWindow: '72h',
    evaluatedAt: '2025-11-18T00:00:00Z',
    cellId: 'cell_tokyo_01',
    cellName: '東京都心・東京湾岸エリア',
    distanceFromEpicenterKm: 0,
    metrics: [
      {
        featureName: 'dog_bark_events',
        displayName: '犬の鳴き声イベント頻度',
        preEventValue: 14.5,
        controlMedian: 5.2,
        changePercentage: +178.8,
        confidenceInterval95: [+95.0, +280.0],
        isStatisticallySignificant: true,
      },
      {
        featureName: 'sound_clipping_events',
        displayName: '低周波環境音響',
        preEventValue: 18.2,
        controlMedian: 6.0,
        changePercentage: +203.3,
        confidenceInterval95: [+110.0, +310.0],
        isStatisticallySignificant: true,
      },
    ],
    verdict: 'no_clear_deviation',
    verdictSummary: '犬の鳴き声と低周波音の観測異常度が78まで急上昇したものの、地震は発生しませんでした。調査の結果、近隣の大規模花火大会・屋外フェスによる音響交絡であることが判明しました。',
    scientificNotes: '科学的説明責任に基づき、地震が起きなかった「偽陽性事例」をカタログ保存しています。人間活動や気象イベントによる交絡因子をリアルタイム分離する重要性を示す重要サンプルです。',
  },
];

// 初期サンプル観測投稿
export const INITIAL_OBSERVATIONS: Observation[] = [
  {
    id: 'obs_demo_01',
    userId: 'user_local_01',
    type: 'audio',
    observedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    cellId: 'cell_tokyo_01',
    cellName: '東京都心・東京湾岸エリア',
    locationApprox: { latitude: 35.68, longitude: 139.76 },
    visibility: 'aggregate_only',
    status: 'finalized',
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    audioAnalysis: {
      id: 'aud_an_01',
      observationId: 'obs_demo_01',
      modelVersion: 'yamnet-v1',
      durationMs: 10000,
      rmsDb: -22.4,
      clippingRatio: 0.0,
      silenceRatio: 0.08,
      speechRatio: 0.02,
      qualityScore: 0.91,
      topLabels: [
        { label: 'Dog', displayName: '犬の鳴き声 (Bark/Howl)', meanScore: 0.74, maxScore: 0.95, frameRatio: 0.52 },
        { label: 'Bird vocalization', displayName: '野鳥のさえずり', meanScore: 0.28, maxScore: 0.54, frameRatio: 0.22 },
        { label: 'Wind', displayName: '風切り音', meanScore: 0.15, maxScore: 0.32, frameRatio: 0.12 },
      ],
      rawAudioDeleted: true,
      completedAt: new Date(Date.now() - 1000 * 60 * 14).toISOString(),
    },
    userConfirmation: {
      confirmedLabels: ['犬の鳴き声 (Bark/Howl)'],
      aiResultCorrect: 'yes',
      userNotes: '近所の散歩中の犬が連続して吠えていた',
    },
  },
  {
    id: 'obs_demo_02',
    userId: 'user_local_02',
    type: 'cloud_photo',
    observedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    cellId: 'cell_chiba_02',
    cellName: '千葉県東部・九十九里沿岸',
    locationApprox: { latitude: 35.53, longitude: 140.45 },
    visibility: 'anonymous_public',
    status: 'finalized',
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    cloudAnalysis: {
      id: 'cld_an_02',
      observationId: 'obs_demo_02',
      modelVersion: 'cloud-vit-v1',
      skyCoverageRatio: 0.85,
      detectedCloudTypes: [
        {
          type: 'altocumulus',
          displayName: '高積雲（波状雲・うろこ雲）',
          description: '上空2000〜6000mの波状の雲。低気圧や前線の接近時に一般的に形成されます。',
          confidence: 0.88,
        },
        {
          type: 'cirrus',
          displayName: '巻雲（すじ雲）',
          description: '上空5000〜13000mの氷晶でできた薄い筋状の雲。',
          confidence: 0.42,
        },
      ],
      qualityScore: 0.89,
      exifStripped: true,
      captureDirection: '南南西',
      captureElevationAngle: 40,
    },
    userConfirmation: {
      confirmedLabels: ['高積雲（波状雲・うろこ雲）'],
      aiResultCorrect: 'yes',
    },
  },
  {
    id: 'obs_demo_03',
    userId: 'user_local_03',
    type: 'citizen_report',
    observedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    cellId: 'cell_chiba_02',
    cellName: '千葉県東部・九十九里沿岸',
    locationApprox: { latitude: 35.53, longitude: 140.45 },
    visibility: 'aggregate_only',
    status: 'finalized',
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    citizenReport: {
      category: 'bird_flock',
      intensity: 3,
      differenceFromNormal: 4,
      durationMinutes: 15,
      description: 'カラスの群れが一斉に南東方向へ飛び交っていた',
    },
  },
];
